version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10.2
    working_directory: /go/src/github.com/the-chris-mitchell/capaci
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go test -v ./...